### ISSUE TITLE
Autori

### ISSUE THREAD

**Issue by grammaton** [dentroprometeo/dentroprometeo.github.io#2]
Questo un modo semplice per inserire l'autore dell'articolo ad ogni articolo

Dentro un `authors.yml`:

```
# Author details.
robert_rawlins:
    name: Robert Rawlins
    email: robert@sorryapp.com
    web: http://twitter.com/sirrawlins
robin_geall:
    name: Robin Geall
    email: robin@sorryapp.com
    web: http://twitter.com/robingeall
```

Dentro il frontmatter di ogni pagina da firmare

```
---
...
# Author.
author: robert_rawlins
---
```

Dentro il layout della pagina post:

```
<!-- Look the author details up from the site config. -->
{% assign author = site.data.authors[page.author] %}

<!-- Output author details if some exist. -->
{% if author %}
    <span>
        <!-- Personal Info. -->
        Written by <a href="{{ author.web }}" target="_blank">{{ author.name }}</a>
    </span>
{% endif %}
```
